### ISSUE TITLE
مشکل در وب سرویس

### ISSUE THREAD

**Issue by ho33ein74** [habibi-dev/Zhaket-product-sales-notification#1]
سلام اکستنشن رو نصب کردم ولی آدرس زیر مشکل داره ممنون میشم راهنمایی کنید که در لینک زیر که استفاده کردید چه کاری باید انجام بشه 
http://zhaket-product-sales-notification.habibi-dev.com/?ZUrl=

**Comment by habibi-dev** [comment]
سلام ممنون از پیام شما دوست عزیز
امشب مشکل بر طرف میشه و مجدد میتوانید از این سرویس استفاده کنید

**Comment by habibi-dev** [comment]
مشکل برطرف شد سرور وبسرویس بالاست

**Comment by habibi-dev** [comment]
فعلا خیر 
ولی در اولین فرصت سعی میکنم بزارم

**Comment by ho33ein74** [comment]
اگه لطف کنید بزارید و یا برام ایمیل کنید ممنون میشم چون واقعا بهش نیاز دارم

**Comment by ho33ein74** [comment]
اگه لطف کنید بزارید و یا برام ایمیل کنید ممنون میشم چون واقعا بهش نیاز دارم
